"""
TMForum eTOM (enhanced Telecom Operations Map) — Business Process Framework
Hierarchical process seed data: Level 1, 2, and 3 processes.

Source: TM Forum GB921 Business Process Framework (eTOM), public specification.
Colours follow the three major areas: SIP (blue), Operations (amber), Enterprise (purple).
"""

SIP_COLOR   = '#2563EB'   # Blue
OPS_COLOR   = '#EA580C'   # Orange
ENT_COLOR   = '#7C3AED'   # Purple

ETOM_PROCESSES = [

    # =========================================================================
    # AREA 1 — STRATEGY, INFRASTRUCTURE & PRODUCT (SIP)
    # =========================================================================
    {
        'code': '1', 'level': 1, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': None,
        'name': 'Strategy, Infrastructure & Product',
        'description': 'Covers the processes that direct strategy and lifecycle management '
                       'of products, services, resources and supply chains.',
    },

    # ── L2: Marketing & Offer Management ─────────────────────────────────────
    {
        'code': '1.1', 'level': 2, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': '1',
        'name': 'Marketing & Offer Management',
        'description': 'Defines the market strategy, plans and manages product/offer portfolio.',
    },
    {'code': '1.1.1', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Market Strategy & Policy',
     'description': 'Establish overall market strategy, competitive positioning and pricing policy.'},
    {'code': '1.1.2', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Product & Offer Portfolio Planning',
     'description': 'Define and maintain the portfolio roadmap of products and bundled offers.'},
    {'code': '1.1.3', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Market Research & Analysis',
     'description': 'Conduct market intelligence, competitor analysis and customer insight research.'},
    {'code': '1.1.4', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Pricing Management',
     'description': 'Develop, maintain and review pricing structures and discount frameworks.'},
    {'code': '1.1.5', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Marketing Communications & Promotions',
     'description': 'Plan and deliver marketing campaigns, promotions and advertising.'},
    {'code': '1.1.6', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.1',
     'name': 'Campaign Management',
     'description': 'End-to-end management of marketing campaigns from concept to measurement.'},

    # ── L2: Product Development & Retirement ─────────────────────────────────
    {
        'code': '1.2', 'level': 2, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': '1',
        'name': 'Product Development & Retirement',
        'description': 'Manages the full lifecycle from new product concept through to retirement.',
    },
    {'code': '1.2.1', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.2',
     'name': 'Product Concept & Feasibility',
     'description': 'Evaluate new product/offer ideas for technical and commercial feasibility.'},
    {'code': '1.2.2', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.2',
     'name': 'Product Design & Specification',
     'description': 'Define detailed product specifications, feature sets and service bundles.'},
    {'code': '1.2.3', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.2',
     'name': 'Product Launch & Release',
     'description': 'Coordinate go-to-market activities, training and readiness for new products.'},
    {'code': '1.2.4', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.2',
     'name': 'Product Lifecycle Management',
     'description': 'Monitor product performance KPIs and manage enhancements over the lifecycle.'},
    {'code': '1.2.5', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.2',
     'name': 'Product Retirement & Migration',
     'description': 'Manage the sunsetting of products and migration of customers to replacements.'},

    # ── L2: Service Development & Management ─────────────────────────────────
    {
        'code': '1.3', 'level': 2, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': '1',
        'name': 'Service Development & Management',
        'description': 'Directs the design, build and lifecycle management of services.',
    },
    {'code': '1.3.1', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.3',
     'name': 'Service Strategy & Planning',
     'description': 'Define service architecture direction and long-range service capabilities.'},
    {'code': '1.3.2', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.3',
     'name': 'Service Design & Testing',
     'description': 'Create detailed service blueprints, test plans and acceptance criteria.'},
    {'code': '1.3.3', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.3',
     'name': 'Service Capability Delivery',
     'description': 'Build, integrate and deploy service components and supporting systems.'},
    {'code': '1.3.4', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.3',
     'name': 'Service Lifecycle Management',
     'description': 'Manage ongoing service performance, enhancements and eventual retirement.'},

    # ── L2: Resource Development & Management ────────────────────────────────
    {
        'code': '1.4', 'level': 2, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': '1',
        'name': 'Resource Development & Management',
        'description': 'Covers technology and network resource strategy, planning and delivery.',
    },
    {'code': '1.4.1', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.4',
     'name': 'Resource Strategy & Planning',
     'description': 'Define long-term resource architecture, technology roadmaps and capacity plans.'},
    {'code': '1.4.2', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.4',
     'name': 'Resource Capability Delivery',
     'description': 'Procure, deploy and integrate hardware, software and infrastructure resources.'},
    {'code': '1.4.3', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.4',
     'name': 'Resource Architecture Management',
     'description': 'Maintain enterprise and solution architecture models for technology resources.'},
    {'code': '1.4.4', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.4',
     'name': 'Resource Retirement & Disposal',
     'description': 'Manage end-of-life decommissioning and disposal of technology assets.'},

    # ── L2: Supply Chain Development & Management ─────────────────────────────
    {
        'code': '1.5', 'level': 2, 'area': 'SIP', 'color': SIP_COLOR,
        'parent_code': '1',
        'name': 'Supply Chain Development & Management',
        'description': 'Manages relationships with suppliers and partners in the value chain.',
    },
    {'code': '1.5.1', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.5',
     'name': 'Supply Chain Strategy & Planning',
     'description': 'Define partner/supplier strategy, sourcing models and procurement frameworks.'},
    {'code': '1.5.2', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.5',
     'name': 'Supply Chain Partner Engagement',
     'description': 'Evaluate, qualify and onboard strategic supplier and partner relationships.'},
    {'code': '1.5.3', 'level': 3, 'area': 'SIP', 'color': SIP_COLOR, 'parent_code': '1.5',
     'name': 'Supply Chain Performance Management',
     'description': 'Monitor supplier KPIs, SLAs and manage continuous improvement in the chain.'},

    # =========================================================================
    # AREA 2 — OPERATIONS
    # =========================================================================
    {
        'code': '2', 'level': 1, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': None,
        'name': 'Operations',
        'description': 'Day-to-day operational processes covering Fulfillment, Assurance, '
                       'Billing and ongoing supplier/partner management.',
    },

    # ── L2: Customer Relationship Management (CRM) ───────────────────────────
    {
        'code': '2.1', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Customer Relationship Management',
        'description': 'End-to-end management of the customer lifecycle: selling, '
                       'order handling, problem resolution, billing inquiry and retention.',
    },
    {'code': '2.1.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Order Handling',
     'description': 'Receive, validate, configure and track customer orders through to fulfilment.'},
    {'code': '2.1.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Problem Handling',
     'description': 'Capture, investigate, escalate and resolve customer-reported problems.'},
    {'code': '2.1.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Customer QoS/SLA Management',
     'description': 'Monitor customer quality of service commitments and manage SLA compliance.'},
    {'code': '2.1.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Bill Inquiry Handling',
     'description': 'Receive, investigate and resolve billing queries and disputes from customers.'},
    {'code': '2.1.5', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Customer Management',
     'description': 'Maintain accurate customer profiles, contacts and account information.'},
    {'code': '2.1.6', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Sales & Channel Management',
     'description': 'Manage sales processes, channels, pipelines and deal closure.'},
    {'code': '2.1.7', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Marketing Fulfillment Response',
     'description': 'Execute direct marketing responses including lead handling and campaign fulfilment.'},
    {'code': '2.1.8', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.1',
     'name': 'Retention & Loyalty Management',
     'description': 'Manage programmes to reduce churn and increase customer lifetime value.'},

    # ── L2: Service Management & Operations ──────────────────────────────────
    {
        'code': '2.2', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Service Management & Operations',
        'description': 'Configuration, activation, quality and problem management of services.',
    },
    {'code': '2.2.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service Configuration & Activation',
     'description': 'Configure and activate service instances to fulfil customer orders.'},
    {'code': '2.2.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service Problem Management',
     'description': 'Detect, diagnose and resolve service-level faults and degradations.'},
    {'code': '2.2.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service Quality Management',
     'description': 'Monitor and report on service quality metrics, trends and thresholds.'},
    {'code': '2.2.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service Fulfillment Monitoring',
     'description': 'Track the status of service provisioning and escalate delivery exceptions.'},
    {'code': '2.2.5', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service & Instance Rating',
     'description': 'Apply usage-based and event-driven rating rules to service instances.'},
    {'code': '2.2.6', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.2',
     'name': 'Service Inventory Management',
     'description': 'Maintain a real-time registry of all provisioned service instances.'},

    # ── L2: Resource Management & Operations ─────────────────────────────────
    {
        'code': '2.3', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Resource Management & Operations',
        'description': 'Provisioning, assurance and performance management of technology resources.',
    },
    {'code': '2.3.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.3',
     'name': 'Resource Provisioning',
     'description': 'Allocate, configure and commission physical and logical resources.'},
    {'code': '2.3.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.3',
     'name': 'Resource Trouble Management',
     'description': 'Detect, isolate, diagnose and restore resource faults.'},
    {'code': '2.3.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.3',
     'name': 'Resource Performance Management',
     'description': 'Collect, analyse and report on resource utilisation and performance data.'},
    {'code': '2.3.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.3',
     'name': 'Resource Data Collection & Processing',
     'description': 'Gather raw usage and event data from network and IT resources.'},
    {'code': '2.3.5', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.3',
     'name': 'Network & IT Inventory Management',
     'description': 'Maintain an accurate logical and physical inventory of all resources.'},

    # ── L2: Supplier/Partner Relationship Management ──────────────────────────
    {
        'code': '2.4', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Supplier/Partner Relationship Management',
        'description': 'Day-to-day operational interaction with suppliers and partners.',
    },
    {'code': '2.4.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.4',
     'name': 'S/P Buying & Procurement',
     'description': 'Raise purchase orders and manage procurement from external suppliers.'},
    {'code': '2.4.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.4',
     'name': 'S/P Settlements & Payments Management',
     'description': 'Validate invoices, manage inter-company settlements and process payments.'},
    {'code': '2.4.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.4',
     'name': 'S/P Problem Reporting & Management',
     'description': 'Report service issues to partners and track resolution to closure.'},
    {'code': '2.4.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.4',
     'name': 'S/P Performance Management',
     'description': 'Measure and report partner/supplier performance against contractual KPIs.'},
    {'code': '2.4.5', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.4',
     'name': 'S/P Contract Management',
     'description': 'Manage the lifecycle of supplier contracts including renewals and amendments.'},

    # ── L2: Operations Support & Readiness ───────────────────────────────────
    {
        'code': '2.5', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Operations Support & Readiness',
        'description': 'Manages workforce, tools and readiness to support FAB operations.',
    },
    {'code': '2.5.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.5',
     'name': 'Workforce Management',
     'description': 'Schedule, dispatch and track field and desk-based operational staff.'},
    {'code': '2.5.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.5',
     'name': 'Fulfillment Support & Readiness',
     'description': 'Ensure systems, processes and skills are ready to execute order fulfilment.'},
    {'code': '2.5.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.5',
     'name': 'Assurance Support & Readiness',
     'description': 'Maintain monitoring tools, NOC capabilities and incident response readiness.'},
    {'code': '2.5.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.5',
     'name': 'Billing Support & Readiness',
     'description': 'Ensure rating, billing and revenue collection systems are operational and accurate.'},

    # ── L2: Billing & Revenue Management ─────────────────────────────────────
    {
        'code': '2.6', 'level': 2, 'area': 'Operations', 'color': OPS_COLOR,
        'parent_code': '2',
        'name': 'Billing & Revenue Management',
        'description': 'End-to-end revenue processing from charging and rating through to collection.',
    },
    {'code': '2.6.1', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Charging',
     'description': 'Apply real-time and batch charging rules to customer usage events.'},
    {'code': '2.6.2', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Bill Invoice Management',
     'description': 'Generate, format, deliver and store customer invoices.'},
    {'code': '2.6.3', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Bill Payments & Receivables Management',
     'description': 'Process customer payments, manage dunning and control receivables.'},
    {'code': '2.6.4', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Billing Mediation & Discounting',
     'description': 'Normalise usage data and apply promotional discounts before rating.'},
    {'code': '2.6.5', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Revenue Management & Analytics',
     'description': 'Analyse revenue trends, leakage and optimisation opportunities.'},
    {'code': '2.6.6', 'level': 3, 'area': 'Operations', 'color': OPS_COLOR, 'parent_code': '2.6',
     'name': 'Revenue Assurance',
     'description': 'Detect and close revenue leakage across all billing and collection processes.'},

    # =========================================================================
    # AREA 3 — ENTERPRISE MANAGEMENT
    # =========================================================================
    {
        'code': '3', 'level': 1, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': None,
        'name': 'Enterprise Management',
        'description': 'Corporate governance, planning, finance, HR, compliance and support '
                       'functions that underpin the whole enterprise.',
    },

    # ── L2: Strategic & Enterprise Planning ──────────────────────────────────
    {
        'code': '3.1', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Strategic & Enterprise Planning',
        'description': 'Sets the overall corporate direction and manages enterprise-wide planning.',
    },
    {'code': '3.1.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.1',
     'name': 'Business Development',
     'description': 'Identify and pursue new business opportunities, M&A and partnerships.'},
    {'code': '3.1.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.1',
     'name': 'Enterprise Architecture Management',
     'description': 'Define and govern enterprise-wide architecture frameworks and standards.'},
    {'code': '3.1.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.1',
     'name': 'Strategic Business Planning',
     'description': 'Formulate, document and cascade multi-year strategic business plans.'},
    {'code': '3.1.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.1',
     'name': 'Corporate Performance Management',
     'description': 'Track and report on enterprise KPIs, OKRs and strategic objectives.'},

    # ── L2: Enterprise Risk, Security & Compliance ────────────────────────────
    {
        'code': '3.2', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Enterprise Risk, Security & Compliance',
        'description': 'Manages risk, cybersecurity, privacy, fraud and regulatory compliance.',
    },
    {'code': '3.2.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Security Management',
     'description': 'Define, implement and operate cybersecurity policies, controls and monitoring.'},
    {'code': '3.2.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Privacy & Data Protection Management',
     'description': 'Ensure compliance with data privacy regulations (GDPR, CCPA, etc.).'},
    {'code': '3.2.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Fraud Management',
     'description': 'Detect, prevent and investigate fraudulent activities across the enterprise.'},
    {'code': '3.2.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Compliance Management',
     'description': 'Ensure adherence to regulatory requirements, standards and internal policies.'},
    {'code': '3.2.5', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Business Continuity & Resilience',
     'description': 'Develop and test DR/BCP plans to maintain operations through disruptions.'},
    {'code': '3.2.6', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.2',
     'name': 'Enterprise Risk Management',
     'description': 'Identify, assess, mitigate and monitor enterprise-wide risks.'},

    # ── L2: Financial & Asset Management ─────────────────────────────────────
    {
        'code': '3.3', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Financial & Asset Management',
        'description': 'Controls financial planning, reporting, cost management and asset ownership.',
    },
    {'code': '3.3.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.3',
     'name': 'Financial Management & Control',
     'description': 'Budgeting, forecasting, financial reporting and management accounting.'},
    {'code': '3.3.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.3',
     'name': 'Cost Management & Optimisation',
     'description': 'Analyse, control and reduce operating costs across the enterprise.'},
    {'code': '3.3.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.3',
     'name': 'Asset Lifecycle Management',
     'description': 'Track and manage enterprise assets from acquisition to disposal.'},
    {'code': '3.3.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.3',
     'name': 'Capital Investment Management',
     'description': 'Govern capital expenditure approvals, tracking and benefits realisation.'},

    # ── L2: Human Resources Management ───────────────────────────────────────
    {
        'code': '3.4', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Human Resources Management',
        'description': 'Manages all aspects of the employee lifecycle and organisational capability.',
    },
    {'code': '3.4.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.4',
     'name': 'Organisational Development & Change',
     'description': 'Design organisational structures and lead change management programmes.'},
    {'code': '3.4.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.4',
     'name': 'Talent Acquisition & Staff Management',
     'description': 'Recruit, onboard and manage the performance of all employees.'},
    {'code': '3.4.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.4',
     'name': 'Workforce Planning',
     'description': 'Forecast and plan headcount, skills gaps and workforce supply.'},
    {'code': '3.4.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.4',
     'name': 'Learning & Development',
     'description': 'Design and deliver training, mentoring and capability development programmes.'},

    # ── L2: Stakeholder & External Relations ──────────────────────────────────
    {
        'code': '3.5', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Stakeholder & External Relations',
        'description': 'Manages regulatory bodies, legal affairs, standards and public relations.',
    },
    {'code': '3.5.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.5',
     'name': 'Regulatory Management',
     'description': 'Engage with regulators, track regulatory change and manage licence obligations.'},
    {'code': '3.5.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.5',
     'name': 'Legal Management',
     'description': 'Manage legal matters, contracts, intellectual property and litigation.'},
    {'code': '3.5.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.5',
     'name': 'Public & Investor Relations',
     'description': 'Manage corporate communications, media relations and investor briefings.'},
    {'code': '3.5.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.5',
     'name': 'Industry & Standards Engagement',
     'description': 'Participate in industry bodies, standards groups and ecosystem initiatives.'},

    # ── L2: Knowledge & Research Management ──────────────────────────────────
    {
        'code': '3.6', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Knowledge & Research Management',
        'description': 'Drives innovation, knowledge capture and intellectual property management.',
    },
    {'code': '3.6.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.6',
     'name': 'Research & Development Management',
     'description': 'Plan and govern R&D investment, experiments and proof-of-concept initiatives.'},
    {'code': '3.6.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.6',
     'name': 'Knowledge Management',
     'description': 'Capture, organise and make accessible organisational knowledge assets.'},
    {'code': '3.6.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.6',
     'name': 'Innovation Management',
     'description': 'Systematically identify, evaluate and incubate innovative ideas and solutions.'},
    {'code': '3.6.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.6',
     'name': 'Intellectual Property Management',
     'description': 'Protect and commercialise patents, trademarks and other IP assets.'},

    # ── L2: Technology & Data Management ─────────────────────────────────────
    {
        'code': '3.7', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Technology & Data Management',
        'description': 'Governs IT strategy, data assets, information security and digital transformation.',
    },
    {'code': '3.7.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.7',
     'name': 'IT Strategy & Planning',
     'description': 'Define IT roadmaps, technology standards and investment priorities.'},
    {'code': '3.7.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.7',
     'name': 'Data Governance & Management',
     'description': 'Establish data ownership, quality standards, catalogues and lineage.'},
    {'code': '3.7.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.7',
     'name': 'Information Security Management',
     'description': 'Define and operate information security controls and incident response.'},
    {'code': '3.7.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.7',
     'name': 'Digital Transformation Management',
     'description': 'Drive enterprise-wide digital initiatives, platform modernisation and adoption.'},
    {'code': '3.7.5', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.7',
     'name': 'Technology Architecture Management',
     'description': 'Maintain and evolve enterprise technology architecture blueprints.'},

    # ── L2: Process Management ────────────────────────────────────────────────
    {
        'code': '3.8', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Process Management',
        'description': 'Design, govern and continuously improve enterprise business processes.',
    },
    {'code': '3.8.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.8',
     'name': 'Process Architecture Management',
     'description': 'Define and maintain the enterprise process architecture and taxonomy.'},
    {'code': '3.8.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.8',
     'name': 'Process Quality Management',
     'description': 'Measure process compliance, efficiency and quality against defined standards.'},
    {'code': '3.8.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.8',
     'name': 'Continuous Process Improvement',
     'description': 'Identify, prioritise and implement process improvement initiatives (Lean, Six Sigma).'},
    {'code': '3.8.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.8',
     'name': 'Business Process Modelling',
     'description': 'Document and maintain process models (BPMN) for operational and compliance use.'},

    # ── L2: Project & Programme Management ───────────────────────────────────
    {
        'code': '3.9', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Project & Programme Management',
        'description': 'Governs the initiation, execution, oversight and closure of projects and programmes.',
    },
    {'code': '3.9.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.9',
     'name': 'Project Portfolio Management',
     'description': 'Prioritise, govern and balance the enterprise project portfolio against strategy.'},
    {'code': '3.9.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.9',
     'name': 'Programme Management',
     'description': 'Coordinate interdependent projects to deliver strategic programme outcomes.'},
    {'code': '3.9.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.9',
     'name': 'Project Assurance & Quality',
     'description': 'Independently review projects for governance compliance and delivery quality.'},
    {'code': '3.9.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.9',
     'name': 'Project Delivery Management',
     'description': 'Plan, execute and control individual projects to time, cost and quality.'},
    {'code': '3.9.5', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.9',
     'name': 'Agile & DevOps Delivery',
     'description': 'Apply agile, scrum and DevOps practices to accelerate IT delivery.'},

    # ── L2: Quality Management ────────────────────────────────────────────────
    {
        'code': '3.10', 'level': 2, 'area': 'Enterprise Management', 'color': ENT_COLOR,
        'parent_code': '3',
        'name': 'Quality Management',
        'description': 'Measures, analyses and improves quality across all enterprise operations.',
    },
    {'code': '3.10.1', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.10',
     'name': 'Performance Assessment',
     'description': 'Conduct periodic assessments of enterprise and operational performance.'},
    {'code': '3.10.2', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.10',
     'name': 'Quality Measurement & Analysis',
     'description': 'Collect quality metrics and analyse root causes of quality defects.'},
    {'code': '3.10.3', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.10',
     'name': 'Quality Improvement Management',
     'description': 'Implement corrective and preventive actions to close quality gaps.'},
    {'code': '3.10.4', 'level': 3, 'area': 'Enterprise Management', 'color': ENT_COLOR, 'parent_code': '3.10',
     'name': 'Customer Experience Management',
     'description': 'Measure NPS, CSAT and CX metrics and drive experience improvement programmes.'},
]
